version: '3.8'

services:
    redis:
        image: redis:latest
        ports:
            - '6379:6379'

    backend:
        build:
            context: .
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '5090:5090'
        environment:
            - NODE_ENV=development
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
        command: npm run start:dev
